### ISSUE TITLE
Please update @actions/core to 1.10.0

### ISSUE THREAD

**Issue by Lucky3028** [keita-hino/get-node-version-from-volta#287]
Hello.
I have been using this Action for a long time. Thank you very much.

Now, I have created this Issue to ask you to update @actions/core. ( #222 )
The background is that GitHub Actions has deprecated save-state and set-output, and GitHub shows that they will not be able to be executed in the near future.

I'm very sorry for your inconvenience, but I would appreciate your response.

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by keita-hino** [comment]
@Lucky3028 
Thanks for creating the issue.
Update of @actions/core is completed.

**Comment by Lucky3028** [comment]
Thank you for your quick response!
